import {Suspense} from 'react'
import { Inter } from "next/font/google";
import "./globals.css";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next js Practice",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<Loading/>}> 
        {children}
        </Suspense>
        </body>
    </html>
  );
}
